name: spring-boot-workflow

on:
  push:
    paths:
      - .github/workflows/spring-boot.yaml
      - spring-blog-example/**

defaults:
  run:
    working-directory: "./spring-blog-example/"

jobs:
  
  build-and-test:
    runs-on: ubuntu-latest
    name: build and test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'      
      - name: Build
        run: |
          mvn clean install -Dmaven.test.skip=true
      - name: Test
        run: |
          mvn test
